package model;

import java.io.Serializable;


public abstract class A_Question implements Serializable {

	private static final long serialVersionUID = -1285366845364926302L; // auto-generated by serializable
	protected static int idGen = 1000; // static id generator
	protected int serialNum; // question id
	protected String quest; // the question
	protected int answerLength; // used only while creating a test for sorting
	
	protected E_QuestionType type;
	
	public A_Question() {
		answerLength=0;
		quest = null;
	}
	public A_Question(String quest) {
		setQuest(quest);
		this.serialNum = idGen++;
		this.answerLength = 0;
	}

	public abstract boolean setAnswerLength();

	public int getAnswerLength() {
		setAnswerLength();
		return answerLength;
	}

	public String getQuest() {
		return quest;
	}
	
	public void setIdGen(int num) {
		idGen = num + 1;
	}

	public boolean setQuest(String quest) { // change the question
		this.quest = quest.trim();
		return true;
	}
	public abstract boolean addAnswer(String answer, boolean isTrue) throws Exception;

	public abstract boolean removeAnswer(int answerIndex);

	public void setSerialNum(int id) {
		this.serialNum = id;
	}
	public int getSerialNum() { // get question id
		return serialNum;
	}

	public E_QuestionType getType() {
		return type;
	}
	
	public abstract boolean isValid();

	public abstract String toStringForTest();

	@Override
	public abstract boolean equals(Object obj);

	@Override
	public abstract String toString();
}
