package model;

import java.io.Serializable;

public class Answer implements Serializable {
	private static final long serialVersionUID = 8915759794416147509L; // auto-generated by serializable
	private static int idGen = 12;
	private String answer; // the answer itself
	private boolean isTrue; // is the answer correct
	private int answerId;
	
	public Answer() {
		this.answerId = idGen;
	}
	public Answer(String answer, boolean isTrue, int id) {
		this.answer = answer.trim();
		this.isTrue = isTrue;
		this.answerId = id;
	}
	public Answer(String answer, boolean isTrue) {
		this.answer = answer.trim();
		this.isTrue = isTrue;
		this.answerId = idGen++;
	}
	
	public Answer(Answer answer) {
		this.answer = answer.getAnswer();
		this.isTrue = answer.getIsTrue();
		this.answerId = answer.getId();
	}

	public int getLength() {
		return answer.length();
	}

	public String getAnswer() {
		return answer;

	}
	
	public void setIdGen(int num) {
		idGen = num + 1;
	}
	
	public void setId(int num) {
		this.answerId = num;
	}
	
	public int getId() {
		return answerId;
	}

	public boolean setAnswer(String answer) {
		answer = answer.trim();
		this.answer = answer;
		return true;
	}

	public boolean getIsTrue() {
		return isTrue;
	}

	public boolean setIsTrue(boolean isTrue) {
		this.isTrue = isTrue;
		return true;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Answer other = (Answer) obj;
		return (answer.compareToIgnoreCase(other.answer) == 0);
	}

	@Override
	public String toString() {
		return "Answer: " + answer + " | The answer is: " + (isTrue ? "" : "IN") + "CORRECT";
	}

}
